schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EnvironmentInput"
  types:
    EnvironmentInput:
      type: object
      description: "Input properties for eks environment."
      required:
        - cluster_name
        - vpc_cidr
        - user
        - kubernetes_version
      properties:
        cluster_name:
          title: "Cluster name"
          type: string
        vpc_cidr:
          title: "VPC CIDR"
          type: string
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
          default: 10.0.0.0/16
        user:
          title: "User"
          type: string
          description: "IAM User for cluster access"
          default: "protondev"
        kubernetes_version:
          title: "Kubernetes version"
          type: string
          enum: ["1.20"]
          default: "1.20"
#        prometheus:
#          title: "Enable Prometheus Add-On"
#          type: boolean
#          default: true
